# Generated by Django 2.2 on 2022-03-01 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20220224_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='course',
            new_name='course_name',
        ),
    ]
