# Generated by Django 2.2 on 2022-03-06 03:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_course_notice'),
        ('operations', '0004_auto_20220301_0134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserComment',
            new_name='CourseComments',
        ),
    ]
